# Generated by Django 3.1.2 on 2021-11-05 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliquizAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_enrolled',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='cliquizAPI.teacher'),
        ),
    ]
