# Generated by Django 3.1.2 on 2021-12-01 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cliquizAPI', '0004_auto_20211201_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.UUIDField(default=uuid.UUID('de2ab449-7593-4611-844e-5c4be7a0d1c2'), editable=False),
        ),
    ]
