# Generated by Django 3.1.2 on 2021-12-01 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cliquizAPI', '0005_auto_20211201_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
