# Generated by Django 3.1.2 on 2021-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliquizAPI', '0006_auto_20211201_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='BCDF50', editable=False, max_length=10),
        ),
    ]
