# Generated by Django 3.1.2 on 2021-12-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliquizAPI', '0007_auto_20211201_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='8DBA7F', editable=False, max_length=10, unique=True),
        ),
    ]
