# Generated by Django 3.1.2 on 2021-12-23 12:51

import cliquiz.cliquizAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliquizAPI', '0009_auto_20211204_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=cliquiz.cliquizAPI.models.unique_course_code, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_avtar',
            field=models.ImageField(upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_avtar',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
