# Generated by Django 3.1.2 on 2022-01-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliquizAPI', '0011_studentcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'course')},
        ),
    ]
