# Generated by Django 3.1.2 on 2022-02-01 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliquizAPI', '0014_auto_20220126_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='ques_type',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='test_id',
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'hidden'), (2, 'deactive')], default=1),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testquestion',
            name='technique',
            field=models.IntegerField(choices=[(0, 'Multiple Choice'), (1, 'Short Answers')], default=0),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question', to='cliquizAPI.test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliquizAPI.course'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='cliquizAPI.testquestion')),
            ],
        ),
    ]
