# Generated by Django 3.1.2 on 2022-02-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliquizAPI', '0016_auto_20220201_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
    ]
